### PR TITLE
Adding notebooks of the basics

### PR DESCRIPTION
**Pull request by snilsn**
Created notebooks for basic functionality and feature detection, ready for revision

### CODE REVIEW

**Comment by fsenf** [comment]
@snilsn : I guess something went wrong with your PR. There are duplicate files in your commit. Why did your split up your notebooks into two subfolders?

**Comment by fsenf** [comment]
@snilsn : Thanks for your contrib!

I guess something went wrong with your PR. 

1. Why are there duplicate files?
2. Why two subfolders?

**Comment by fsenf** [comment]
Ahhh, duplicate comment .... more concentration is needed ;-)

**Comment by snilsn** [comment]
Oh, I missed to delete the old 'Tutorial'-folder, which was kinda badly named if we are already in the 'tutorial'-directory :)

done now

**Comment by fsenf** [comment]
nice work thanks

**Pull request merged**
